### ISSUE TITLE
TODO -> Project Ideas

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/waifuland-api#3]
### TODO
- [x] Deploy 
- [x] Build upload method
- [x] Build random method
- [x] Middleware for images
- [x] JWT
- [x] Middleware for GET/POST Methods 
- [x] Change mongoose for TypeORM (Cancelled didn't like TypeORM for mongodb at all.)
- [x] Migrate from render to AWS EC2
- [x] Add filters
- [x] Dockerize App
- [x] Get a public domain 
- [x] Populate the database with at least 200 images

**Comment by jd-apprentice** [comment]
Random method implemented here -> PR #2

**Comment by jd-apprentice** [comment]
@all-contributors please add @jd-apprentice for code, test, doc and maintenance

**Comment by jd-apprentice** [comment]
- [x] Add passport to protect post method in production #8

**Comment by jd-apprentice** [comment]
- [x] Middleware for GET/POST Methods #10

**Comment by jd-apprentice** [comment]
DB Now has around 40 images? I'll be uploading more of them soon

**Comment by jd-apprentice** [comment]
- [x] Middleware of images now has a ```fileFilter``` function that only accepts jpg/png #12

**Comment by jd-apprentice** [comment]
I'm making some improvements for the project structure then I'll be adding filters

**Comment by jd-apprentice** [comment]
- [ ] Added a reference entity into another #20

**Comment by jd-apprentice** [comment]
I'll be changing mongoose for TypeORM

**Comment by jd-apprentice** [comment]
> I'll be changing mongoose for TypeORM

I tried this and TypeORM with mongodb is not as good as mongoose, I stay like this and use Typeorm for others projects. Next i'm going to add a development environment since all this time I've been doing all the test in the production environment which is not optimal at this point. Also i've learn a little bit of AWS so.. I may try to migrate from Render to a EC2 Instance of AWS

**Comment by jd-apprentice** [comment]
Db has around 80 images right now

**Comment by jd-apprentice** [comment]
Filter for `tag_id` 

- [x] added on #29

**Comment by jd-apprentice** [comment]
Docker added

- [x] Dockerize App #34

**Comment by jd-apprentice** [comment]
- [x] Migrate from render to AWS (Instead I took digital ocean)
- [x] Get a public domain -> [waifuland](https://waifuland.jonathan.com.ar/)
