### ISSUE TITLE
Todo -> Frontend

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/waifuland-api#7]
- [x] Choose a framework (react, angular or svelte)
- [x] Build simple frontend as documentation/landing page
- [x] Build a login page
- [x] Redirect to login if the token expires

**Comment by jd-apprentice** [comment]
Front as been build with

- React
- Typescript
- Mui
- Sass

**Comment by jd-apprentice** [comment]
I'm lazy as fuck with the frontend i'm sorry lmao, I'll try to at least document a little when I finish other stuff.

**Comment by jd-apprentice** [comment]
Frontend is being updated here now -> [link](https://github.com/jd-apprentice/waifuland-fe/issues/10)
